


FC = s.f90
CXX = s.cc



SOURCES_C = $(wildcard *.c) 
SOURCES_F = $(wildcard *.f)
OBJ = $(patsubst %.c, %.o, $(notdir $(SOURCES_C)))
      #$(patsubst %.f, %.o, $(notdir $(SOURCES_F))) 
	


all : $(OBJ)
	@echo $(OBJ)
	$(FC) -shared $(OBJ) -o rmnlib.so -lrmnshared_013  #:-lrmn_013 -lc -lpgc -lpgf90 -lpgf90_rpm1 -lpgf902 -lnetcdf_c++ -lnetcdf -pgf90libs

%.o : %.cpp
	$(CXX) -c -g -fPIC $< -o $@ $(INCLUDE)

clean:
	rm -f *.o
	rm -f *.so
