


FC = s.f90
CC = s.cc



SOURCES_C = $(wildcard *.c) 
SOURCES_F = $(wildcard *.f)
OBJ = $(patsubst %.c, %.o, $(notdir $(SOURCES_C))) \
      $(patsubst %.f, %.o, $(notdir $(SOURCES_F))) 
	

all : $(OBJ)
	@echo $(OBJ)
	USE_PIC=yes $(FC) -shared $(OBJ) -o rmnlib.so -lrmnshared_013  #:-lrmn_013 -lc -lpgc -lpgf90 -lpgf90_rpm1 -lpgf902 -lnetcdf_c++ -lnetcdf -pgf90libs

%.o : %.c
	USE_PIC=yes $(CC) -c -g  $< -o $@

%.o : %.f
	USE_PIC=yes $(FC) -c -g $< -o $@



clean:
	rm -f $(OBJ)
	rm -f *.so
